columnas

Index(['Pais', 
       'Pais_Cod', 
       'Anio', 
       'Anio_Cod',
       'Acceso a Cocina Limpia (% poblacion)',
       'Acceso a Electricidad (% poblacion)',
       'Tierra Agricola Irrigada (% tierra agricola)',
       'Tierra Agricola (% area terrestre)', 
       'Tierra Agricola (km2)',
       'Emisiones de Metano Agricola (% total)',
       'Emisiones de Metano Agricola (kton CO2eq)',
       'Emisiones de Oxido Nitroso Agricola (% total)',
       'Emisiones de Oxido Nitroso Agricola (kton CO2eq)',
       'Energia Alternativa y Nuclear (% uso energia)',
       'Extraccion Anual de Agua Dulce, Agricultura (% total extraccion agua dulce)',
       'Extraccion Anual de Agua Dulce, Domestica (% total extraccion agua dulce)',
       'Extraccion Anual de Agua Dulce, Industria (% total extraccion agua dulce)',
       'Extraccion Anual de Agua Dulce, Total (% recursos internos)',
       'Extraccion Anual de Agua Dulce, Total (km3)',
       'Tierra Arable (% area terrestre)',
       'Produccion de Acuicultura (ton Metricas)',
       'Tierra Arable (ha por persona)', 
       'Tierra Arable (ha)',
       'Precipitacion Promedio (mm por ano)',           
       'Especies de Aves Amenazadas',
       'Produccion de Pesca de Captura (ton Metricas)',
       'Produccion de Cereales (ton Metricas)',
       'Rendimiento de Cereales (kg por ha)', 
       'Emisiones de CO2 (kton)',
       'Emisiones de CO2 per capita (ton)',
       'Sequias, Inundaciones, Temperaturas Extremas (% poblacion, promedio 1990-2009)',
       'Consumo de Energia Electrica (kWh per capita)',
       'Uso de Energia (kg de equivalente de petroleo per capita)',
       'Consumo de Fertilizantes (% produccion de fertilizantes)',
       'Consumo de Fertilizantes (kg por ha de tierra arable)',
       'Especies de Peces Amenazadas', 
       'Area de Bosque (% area terrestre)',
       'Area de Bosque (km2)',
       'Consumo de Energia de Combustibles Fosiles (% total)',
       'Area de Tierra (km2)', 
       'Tierra bajo Produccion de Cereales (ha)',
       'Especies de Mamiferos Amenazadas', 
       'Emisiones de Metano (kton CO2eq)',
       'Especies de Plantas Amenazadas',
       'Contaminacion del Aire PM2.5, Exposicion Anual Promedio (ug/m3)',
       'Densidad de Poblacion (personas por km2)',
       'Poblacion en la Ciudad Mas Grande',
       'Poblacion en la Ciudad Mas Grande (% poblacion urbana)',
       'Consumo de Energia Renovable (% total consumo final de energia)',
       'Area de Tierra Rural (km2)', 
       'Poblacion Rural',
       'Poblacion Rural (% poblacion total)',
       'Crecimiento de la Poblacion Rural (anual %)',
       'Area de Superficie (km2)',
       'Areas Protegidas Terrestres y Marinas (% area territorial total)',
       'Areas Protegidas Terrestres (% area de tierra total)',
       'Produccion Total de Pesca (ton Metricas)',
       'Emisiones Totales de Gases de Efecto Invernadero (kton CO2eq)',
       'Area de Tierra Urbana (km2)', 
       'Poblacion Urbana',
       'Poblacion Urbana (% poblacion total)',
       'Crecimiento de la Poblacion Urbana (anual %)', 
       'Poblacion Total'],
      dtype='object')